### ISSUE TITLE
PyPrimeMesh link in PyAnsys site needs updating

### ISSUE THREAD

**Issue by waltersma** [ansys/pyansys#308] opened 2023-07-19 07:29 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

[PyAnsys — PyAnsys](https://docs.pyansys.com/version/stable/)
link still pointing to 0.3.2 docs for PyPrimeMesh.  Please can we update to 0.4.0.

### 📝 Steps to reproduce

Click on link to PyPrimeMesh in [PyAnsys — PyAnsys](https://docs.pyansys.com/version/stable/)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

N/A

### 🐍 Which Python version are you using?

3.7

### 📦 Installed packages

```shell
N/A
```

**Comment by RobPasMue** [comment] 2023-07-19 07:49
Hi @waltersma - The PyAnsys metapackage for version 2023.2 is indeed pointing towards 0.3.2. But this is intended. The new PyPrimeMesh version is not part of the 2023.2 release. If you look at the ``dev`` version of the metapackage though, you will get redirected to the latest stable version of PyPrimeMesh.

Closing this issue since it is the intended behavior. We can keep discussing it here though if you have any doubts.

**Closed by RobPasMue** 2023-07-19 07:49 UTC
Labels: bug
